In [3]:
!pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\mithu\appdata\roaming\python\python313\site-packages (2.9.11)

In [19]:
import urllib.parse

In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [5]:
data = pd.read_csv(r"C:\Users\mithu\OneDrive\Desktop\Data_Analytics\Flipkart_Consolidated_Daily_Report(Sep'1-Sep'30).csv",skiprows=2)

In [6]:
data.head()

,Campaign ID,Campaign Name,Ad Group ID,AdGroup Name,Date,Views,Clicks,CTR,CVR,Ad Spend,Units Sold (Direct),Units Sold (Indirect),Direct Revenue,Indirect Revenue,ROI (Direct),ROI (Indirect)
0,LPSY0XN6QNEM,HM_NAT_PLA_Auto_Pressure_Cooker_Xpress_Triply,PZ4F98HMWA8U,"Kitchen, Cookware & Serveware",2025-10-05,48141,892,1.8529,0.2242,2082.8,2,0,8908.0,0.0,4.2769,0.0
1,MGLA52XVA4WQ,HM_NAT_PLA_Auto_Mixed_Lower_AOV_Products,3C8KAMHBMTE9,"Kitchen, Cookware & Serveware",2025-10-13,8142,126,1.5475,0.0000,835.4,0,0,0.0,0.0,0.0000,0.0
2,G8J4A7EW9EPP,HM_NAT_PLA_Generic_PM_Khadai_ToS_Page,BDK81TWAA8NZ,"Kitchen, Cookware & Serveware",2025-10-04,69,1,1.4493,0.0000,3.0,0,0,0.0,0.0,0.0000,0.0
3,V7JWJKHCPBWZ,HM_NAT_PLA_Comp_Tawa_Artisan_Hybrid_Triply,A40VBYHD6ER7,"Kitchen, Cookware & Serveware",2025-10-22,897,10,1.1148,0.0000,19.5,0,0,0.0,0.0,0.0000,0.0
4,B03KFE2M5P4Z,HM_NAT_PLA_Auto_Frying_Pan_Artisan_Triply_New,5Y1BOKTIB2LC,"Kitchen, Cookware & Serveware",2025-10-02,476,7,1.4706,0.0000,18.0,0,0,0.0,0.0,0.0000,0.0

In [7]:
data.tail()

,Campaign ID,Campaign Name,Ad Group ID,AdGroup Name,Date,Views,Clicks,CTR,CVR,Ad Spend,Units Sold (Direct),Units Sold (Indirect),Direct Revenue,Indirect Revenue,ROI (Direct),ROI (Indirect)
921,V4USEMHJFNFH,HM_NAT_PLA_Generic_EM_Tawa_Artisan_Hybrid_New,M37CFXRLANCA,"Kitchen, Cookware & Serveware",2025-10-18,1098,15,1.3661,0.0000,60.00,0,0,0.0,0.0,0.0000,0.0
922,Y6QUG8IUV06X,HM_NAT_PLA_Auto_Mixed_Browse_Page,QAPY9AGVLPQL,"Kitchen, Cookware & Serveware",2025-10-21,93674,1029,1.0985,0.2915,3420.50,3,0,10114.0,0.0,2.9569,0.0
923,8X1SYT76XR7S,HM_NAT_PLA_Generic_PM_Frying_Pan_Artisan_Tripl...,J1G26O3SYZDL,"Kitchen, Cookware & Serveware",2025-10-03,2355,22,0.9342,0.0000,74.35,0,0,0.0,0.0,0.0000,0.0
924,0BUR0MSCV9PA,HM_NAT_PLA_Generic_Pressure_Cooker_Catch_All,HS55J0XKKVYL,"Kitchen, Cookware & Serveware",2025-10-14,16321,215,1.3173,0.0000,966.63,0,0,0.0,0.0,0.0000,0.0
925,WYHADIPCOOFH,HM_NAT_PLA_Generic_PM_Tawa_Artisan_Hybrid_Triply,7J0VXVH38R2H,"Kitchen, Cookware & Serveware",2025-10-24,837,17,2.0311,0.0000,34.49,0,0,0.0,0.0,0.0000,0.0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 926 entries, 0 to 925
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Campaign ID            926 non-null    object
 1   Campaign Name          926 non-null    object
 2   Ad Group ID            926 non-null    object
 3   AdGroup Name           926 non-null    object
 4   Date                   926 non-null    object
 5   Views                  926 non-null    int64
 6   Clicks                 926 non-null    int64
 7   CTR                    926 non-null    float64
 8   CVR                    926 non-null    float64
 9   Ad Spend               926 non-null    float64
 10  Units Sold (Direct)    926 non-null    int64
 11  Units Sold (Indirect)  926 non-null    int64
 12  Direct Revenue         926 non-null    float64
 13  Indirect Revenue       926 non-null    float64
 14  ROI (Direct)           926 non-null    float64
 15  ROI (Indirect)         926 non-null    float64
dtypes: float64(7), int64(4), object(5)
memory usage: 115.9+ KB

In [9]:
data.isnull().sum()

Campaign ID              0
Campaign Name            0
Ad Group ID              0
AdGroup Name             0
Date                     0
Views                    0
Clicks                   0
CTR                      0
CVR                      0
Ad Spend                 0
Units Sold (Direct)      0
Units Sold (Indirect)    0
Direct Revenue           0
Indirect Revenue         0
ROI (Direct)             0
ROI (Indirect)           0
dtype: int64

In [20]:
db_username = 'postgres'
db_password = urllib.parse.quote_plus('mithun@4088')
db_host = 'localhost'
db_port = 5432 
db_name = 'Flipkart'

In [21]:
connection = create_engine(f'postgresql+psycopg2://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}')

In [22]:
data.to_sql('Daily_Report_Sep', connection, if_exists = 'replace', index = False)
connection.dispose()